@host = http://localhost:8080
# 전체 조회 후 id 설정
@id = 59

### 0. 전체 조회 (id 확인용)
GET {{host}}/api/books

### 1-1. 등록 (post)
POST {{host}}/api/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "isbn": "9780132350884",
  "price": 45,
  "publishDate": "2008-08-01",
  "detailRequest": {
    "description": "A handbook of agile software craftsmanship",
    "language": "English",
    "pageCount": 464,
    "publisher": "Prentice Hall",
    "coverImageUrl": "https://example.com/cleancode.jpg",
    "edition": "1st"
  }
}

### 1-2. 등록 (post)
POST {{host}}/api/books
Content-Type: application/json

{
  "title": "Effective Java",
  "author": "Joshua Bloch",
  "isbn": "9780134685991",
  "price": 55,
  "publishDate": "2017-12-27",
  "detailRequest": {
    "description": "The definitive guide to Java programming language",
    "language": "English",
    "pageCount": 416,
    "publisher": "Addison-Wesley",
    "coverImageUrl": "https://example.com/effectivejava.jpg",
    "edition": "3rd"
  }
}

### 2. ISBN으로 책 조회 (GET)
GET {{host}}/api/books/isbn/9780132350884

### 3-1. 저자로 책 검색
GET {{host}}/api/books/search/author?author=Robert

### 3-2. 제목으로 책 검색
GET {{host}}/api/books/search/title?title=Clean

### 4. 수정 (PUT) - 전체수정
# 전체 조회 후 id 설정
PUT {{host}}/api/books/{{id}}
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "isbn": "9780132350884",
  "price": 45,
  "publishDate": "2008-08-01",
  "detailRequest": {
    "description": "A handbook of agile software craftsmanship",
    "language": "English",
    "pageCount": 464,
    "publisher": "Prentice Hall",
    "coverImageUrl": "https://example.com/cleancode.jpg",
    "edition": "1st"
  }
}

### 4-1. (제목만 수정) PATCH
PATCH {{host}}/api/books/{{id}}
Content-Type: application/json

{ "title": "새로운 제목" }

### 4-2. 가격과 언어만 수정 PATCH
PATCH {{host}}/api/books/{{id}}
Content-Type: application/json

{
  "price": 15000,
  "detailRequest": { "language": "Korean" }
}

### 4-3. BookDetail의 설명만 수정 PATCH
PATCH {{host}}/api/books/{{id}}/detail
Content-Type: application/json

{ "description": "새로운 책 설명" }
